# config_version=3

config:
    - hardware.yaml
    - keyboard.yaml
    - window.yaml

modes:
  - base
  - tilt
  - high_score
  - bonus
  - carousel
  - mode_1
  - mode_2
  - wizard_mode

game:
  balls_per_game: 3
  max_players: 4

machine:
  glass_off_mode: true