# config_version=3

config:
  - config.yaml

switch_player:
  start_event: machine_reset_phase_3
  start_delay: 1s
  steps:
    - time: 100ms
      switch: trough_1
      action: activate
    - time: 600ms
      switch: start
      action: hit
    - time: 100ms
      switch: trough_1
      action: deactivate
    - time: 100ms
      switch: plunger_lane
      action: activate
    - time: 1s
      switch: right_flipper
      action: hit
    - time: 1s
      switch: right_flipper
      action: hit
    - time: 1s
      switch: right_flipper
      action: hit
    - time: 1s
      switch: right_flipper
      action: hit
    - time: 1s
      switch: right_flipper
      action: hit
    - time: 1s
      switch: plunger_lane
      action: deactivate
    - time: 1s
      switch: right_flipper
      action: hit